version: '3.0'

expectations:
  population_size: 500000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  cox_ipw:
    # For user-facing documentation, call:
    # cox-ipw:[version]
    run: r:latest analysis/cox-ipw.R
    needs:
    - generate_study_population
    outputs:
      highly_sensitive:
        analysis_ready: output/ready-*.csv.gz
      moderately_sensitive:
        arguments: output/args-results.csv
        estimates: output/results.csv

  # Test the action works in the system and with a flag
  # cox_ipw_2:
  #   run: >
  #     cox-ipw:v0.0.1
  #       --df_output=results_2.csv
  #   needs:
  #   - generate_study_population
  #   outputs:
  #       moderately_sensitive:
  #         arguments: output/args-results_2.csv
  #         estimates: output/results_2.csv
