version: '3.0'

expectations:
  population_size: 500000

actions:

  generate_study_population:
    run: r:v2 analysis/move-test-data.R
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  cox_ipw:
    # For user-facing documentation, call:
    # cox-ipw:[version]
    run: r:v2 analysis/cox-ipw.R --df_input input.csv
    needs:
    - generate_study_population
    outputs:
      # uncomment and reindent the lines below when saving the analysis ready dataset
      # highly_sensitive:
      #   analysis_ready: output/ready-*.csv.gz
      moderately_sensitive:
        arguments: output/args-results.csv
        estimates: output/results.csv

  cox_ipw_2:
    run: r:v2 analysis/cox-ipw.R
    config:
      df_output: results-2.csv
    needs:
    - generate_study_population
    outputs:
      moderately_sensitive:
        arguments: output/args-results-2.csv
        estimates: output/results-2.csv
