version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  cox_ipw:
    run: r:latest analysis/cox-ipw.R
    needs:
    - generate_study_population
    outputs:
        moderately_sensitive:
          arguments: output/args-results.csv
          estimates: output/results.csv
