version: '3.0'

expectations:
  population_size: 500000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  cox_ipw:
    # For user-facing documentation, call:
    # cox-ipw:[version]
    run: r:v2 analysis/cox-ipw.R
    needs:
    - generate_study_population
    outputs:
      # uncomment and reindent the lines below when saving the analysis ready dataset
      # highly_sensitive:
      #   analysis_ready: output/ready-*.csv.gz
      moderately_sensitive:
        arguments: output/args-results.csv
        estimates: output/results.csv
